alter table public.produtos
    add column if not exists avaliacao_media numeric(2, 1) not null default 4.5,
    add column if not exists total_avaliacoes int not null default 0,
    add column if not exists feedback_destaque text;

create table if not exists public.avaliacoes_produto (
    id_avaliacao int generated by default as identity primary key,
    id_produto int not null references public.produtos(id_produto) on delete cascade,
    auth_id uuid references auth.users(id) on delete set null,
    nota int not null check (nota between 1 and 5),
    comentario text,
    data_avaliacao timestamptz not null default now()
);

alter table public.avaliacoes_produto enable row level security;

drop policy if exists "qualquer usuario ve avaliacoes dos produtos" on public.avaliacoes_produto;
create policy "qualquer usuario ve avaliacoes dos produtos"
on public.avaliacoes_produto
for select
to anon, authenticated
using (true);

drop policy if exists "usuario autenticado avalia produto" on public.avaliacoes_produto;
create policy "usuario autenticado avalia produto"
on public.avaliacoes_produto
for insert
to authenticated
with check (auth.uid() = auth_id);

drop policy if exists "admin gerencia avaliacoes" on public.avaliacoes_produto;
create policy "admin gerencia avaliacoes"
on public.avaliacoes_produto
for all
to authenticated
using (public.current_user_is_admin())
with check (public.current_user_is_admin());

create or replace function public.recalcular_avaliacao_produto()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    produto_id int;
begin
    produto_id := coalesce(new.id_produto, old.id_produto);

    update public.produtos produto
    set
        avaliacao_media = coalesce((
            select round(avg(nota)::numeric, 1)
            from public.avaliacoes_produto avaliacao
            where avaliacao.id_produto = produto_id
        ), 4.5),
        total_avaliacoes = (
            select count(*)::int
            from public.avaliacoes_produto avaliacao
            where avaliacao.id_produto = produto_id
        ),
        feedback_destaque = coalesce((
            select comentario
            from public.avaliacoes_produto avaliacao
            where avaliacao.id_produto = produto_id
              and nullif(trim(avaliacao.comentario), '') is not null
            order by avaliacao.data_avaliacao desc
            limit 1
        ), produto.feedback_destaque)
    where produto.id_produto = produto_id;

    return coalesce(new, old);
end;
$$;

drop trigger if exists trigger_recalcular_avaliacao_produto on public.avaliacoes_produto;

create trigger trigger_recalcular_avaliacao_produto
after insert or update or delete on public.avaliacoes_produto
for each row execute function public.recalcular_avaliacao_produto();

grant select on public.avaliacoes_produto to anon, authenticated;
grant insert on public.avaliacoes_produto to authenticated;
grant update, delete on public.avaliacoes_produto to authenticated;
grant usage, select on sequence public.avaliacoes_produto_id_avaliacao_seq to authenticated;
grant execute on function public.recalcular_avaliacao_produto() to authenticated;
