begin transaction;

drop table if exists pagamentos cascade;
drop table if exists itens_pedido cascade;
drop table if exists pedidos cascade;
drop table if exists fretes cascade;
drop table if exists rasas cascade;
drop table if exists enderecos cascade;
drop table if exists clientes cascade;
drop table if exists usuario_perfil cascade;
drop table if exists perfis cascade;
drop table if exists produtos cascade;
drop table if exists categorias cascade;
drop table if exists usuarios cascade;

create table if not exists usuarios (
    id_usuario int generated by default as identity primary key,
    nome varchar not null,
    email varchar not null unique,
    senha_hash varchar not null,
    status varchar not null default 'ATIVO',
    data_cadastro timestamp not null default now(),
    ultimo_acesso timestamp
);

create table if not exists perfis (
    id_perfil int generated by default as identity primary key,
    nome varchar not null unique,
    descricao text
);

create table if not exists usuario_perfil (
    id_usuario int not null references usuarios(id_usuario) on delete cascade,
    id_perfil int not null references perfis(id_perfil) on delete cascade,
    primary key (id_usuario, id_perfil)
);

create table if not exists clientes (
    id_cliente int generated by default as identity primary key,
    id_usuario int unique references usuarios(id_usuario) on delete cascade,
    auth_id uuid unique,
    is_admin boolean not null default false,
    nome text,
    email text,
    cpf varchar unique,
    telefone varchar,
    data_nascimento date
);

create table if not exists enderecos (
    id_endereco int generated by default as identity primary key,
    id_cliente int not null references clientes(id_cliente) on delete cascade,
    cep varchar,
    logradouro varchar not null,
    numero varchar not null,
    complemento varchar,
    bairro varchar not null,
    cidade varchar not null,
    estado varchar not null,
    tipo varchar,
    principal boolean not null default false
);

create table if not exists categorias (
    id_categoria int generated by default as identity primary key,
    nome varchar not null,
    descricao text,
    status varchar not null default 'ATIVA'
);

create table if not exists produtos (
    id_produto int generated by default as identity primary key,
    id_categoria int references categorias(id_categoria),
    nome varchar not null,
    descricao text,
    preco decimal(10, 2) not null,
    estoque int not null default 0,
    imagem varchar,
    ingredientes text,
    status varchar not null default 'ATIVO',
    data_cadastro timestamp not null default now()
);

create table if not exists pedidos (
    id_pedido int generated by default as identity primary key,
    id_cliente int not null references clientes(id_cliente),
    id_endereco_entrega int not null references enderecos(id_endereco),
    data_pedido timestamp not null default now(),
    status varchar not null,
    valor_frete decimal(10, 2) not null default 0,
    valor_total decimal(10, 2) not null
);

create table if not exists itens_pedido (
    id_item int generated by default as identity primary key,
    id_pedido int not null references pedidos(id_pedido) on delete cascade,
    id_produto int not null references produtos(id_produto),
    quantidade int not null,
    preco_unitario decimal(10, 2) not null,
    subtotal decimal(10, 2) not null
);

create table if not exists pagamentos (
    id_pagamento int generated by default as identity primary key,
    id_pedido int not null references pedidos(id_pedido) on delete cascade,
    metodo varchar not null,
    valor decimal(10, 2) not null,
    status varchar not null,
    data_pagamento timestamp,
    codigo_transacao varchar
);

insert into perfis (nome, descricao)
values
    ('CLIENTE', 'Cliente do e-commerce'),
    ('ADMIN', 'Administrador do sistema'),
    ('ESTOQUISTA', 'Usuario responsavel pelo estoque')
on conflict (nome) do nothing;

alter table categorias enable row level security;
alter table produtos enable row level security;
alter table clientes enable row level security;
alter table enderecos enable row level security;
alter table pedidos enable row level security;
alter table itens_pedido enable row level security;
alter table pagamentos enable row level security;

create or replace function public.current_user_is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
    select exists (
        select 1
        from clientes
        where clientes.auth_id = auth.uid()
          and clientes.is_admin = true
    );
$$;

drop policy if exists "Leitura publica de categorias" on categorias;
create policy "Leitura publica de categorias"
on categorias
for select
to anon, authenticated
using (status = 'ATIVA');

drop policy if exists "Leitura publica de produtos" on produtos;
create policy "Leitura publica de produtos"
on produtos
for select
to anon, authenticated
using (status = 'ATIVO');

drop policy if exists "Cliente ve o proprio perfil" on clientes;
create policy "Cliente ve o proprio perfil"
on clientes
for select
to authenticated
using (auth_id = auth.uid());

drop policy if exists "Cliente cria o proprio perfil" on clientes;
create policy "Cliente cria o proprio perfil"
on clientes
for insert
to authenticated
with check (auth_id = auth.uid());

drop policy if exists "Admin ve clientes" on clientes;
create policy "Admin ve clientes"
on clientes
for select
to authenticated
using (public.current_user_is_admin());

drop policy if exists "Cliente gerencia seus enderecos" on enderecos;
create policy "Cliente gerencia seus enderecos"
on enderecos
for all
to authenticated
using (
    exists (
        select 1 from clientes
        where clientes.id_cliente = enderecos.id_cliente
          and clientes.auth_id = auth.uid()
    )
)
with check (
    exists (
        select 1 from clientes
        where clientes.id_cliente = enderecos.id_cliente
          and clientes.auth_id = auth.uid()
    )
);

drop policy if exists "Cliente ve seus pedidos" on pedidos;
create policy "Cliente ve seus pedidos"
on pedidos
for select
to authenticated
using (
    exists (
        select 1 from clientes
        where clientes.id_cliente = pedidos.id_cliente
          and clientes.auth_id = auth.uid()
    )
);

drop policy if exists "Cliente cria seus pedidos" on pedidos;
create policy "Cliente cria seus pedidos"
on pedidos
for insert
to authenticated
with check (
    exists (
        select 1 from clientes
        where clientes.id_cliente = pedidos.id_cliente
          and clientes.auth_id = auth.uid()
    )
);

drop policy if exists "Cliente ve seus itens" on itens_pedido;
create policy "Cliente ve seus itens"
on itens_pedido
for select
to authenticated
using (
    exists (
        select 1
        from pedidos
        join clientes on clientes.id_cliente = pedidos.id_cliente
        where pedidos.id_pedido = itens_pedido.id_pedido
          and clientes.auth_id = auth.uid()
    )
);

drop policy if exists "Cliente cria itens dos seus pedidos" on itens_pedido;
create policy "Cliente cria itens dos seus pedidos"
on itens_pedido
for insert
to authenticated
with check (
    exists (
        select 1
        from pedidos
        join clientes on clientes.id_cliente = pedidos.id_cliente
        where pedidos.id_pedido = itens_pedido.id_pedido
          and clientes.auth_id = auth.uid()
    )
);

drop policy if exists "Cliente ve pagamentos dos seus pedidos" on pagamentos;
create policy "Cliente ve pagamentos dos seus pedidos"
on pagamentos
for select
to authenticated
using (
    exists (
        select 1
        from pedidos
        join clientes on clientes.id_cliente = pedidos.id_cliente
        where pedidos.id_pedido = pagamentos.id_pedido
          and clientes.auth_id = auth.uid()
    )
);

drop policy if exists "Cliente cria pagamentos dos seus pedidos" on pagamentos;
create policy "Cliente cria pagamentos dos seus pedidos"
on pagamentos
for insert
to authenticated
with check (
    exists (
        select 1
        from pedidos
        join clientes on clientes.id_cliente = pedidos.id_cliente
        where pedidos.id_pedido = pagamentos.id_pedido
          and clientes.auth_id = auth.uid()
    )
);

drop policy if exists "Admin gerencia produtos" on produtos;
create policy "Admin gerencia produtos"
on produtos
for all
to authenticated
using (public.current_user_is_admin())
with check (public.current_user_is_admin());

drop policy if exists "Admin gerencia categorias" on categorias;
create policy "Admin gerencia categorias"
on categorias
for all
to authenticated
using (public.current_user_is_admin())
with check (public.current_user_is_admin());

drop policy if exists "Admin ve itens dos pedidos" on itens_pedido;
create policy "Admin ve itens dos pedidos"
on itens_pedido
for select
to authenticated
using (public.current_user_is_admin());

drop policy if exists "Admin gerencia pedidos" on pedidos;
create policy "Admin gerencia pedidos"
on pedidos
for all
to authenticated
using (public.current_user_is_admin())
with check (public.current_user_is_admin());

drop policy if exists "Admin gerencia pagamentos" on pagamentos;
create policy "Admin gerencia pagamentos"
on pagamentos
for all
to authenticated
using (public.current_user_is_admin())
with check (public.current_user_is_admin());

grant usage on schema public to anon, authenticated;
grant select on categorias, produtos to anon, authenticated;
grant select, insert, update on clientes, enderecos, pedidos, itens_pedido, pagamentos, produtos, categorias to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.current_user_is_admin() to authenticated;

commit;
