begin transaction;

drop table if exists pagamentos cascade;
drop table if exists itens_pedido cascade;
drop table if exists pedidos cascade;
drop table if exists fretes cascade;
drop table if exists rasas cascade;
drop table if exists enderecos cascade;
drop table if exists clientes cascade;
drop table if exists usuario_perfil cascade;
drop table if exists perfis cascade;
drop table if exists produtos cascade;
drop table if exists categorias cascade;
drop table if exists usuarios cascade;

create table if not exists usuarios (
    id_usuario int generated by default as identity primary key,
    nome varchar not null,
    email varchar not null unique,
    senha_hash varchar not null,
    status varchar not null default 'ATIVO',
    data_cadastro timestamp not null default now(),
    ultimo_acesso timestamp
);

create table if not exists perfis (
    id_perfil int generated by default as identity primary key,
    nome varchar not null unique,
    descricao text
);

create table if not exists usuario_perfil (
    id_usuario int not null references usuarios(id_usuario) on delete cascade,
    id_perfil int not null references perfis(id_perfil) on delete cascade,
    primary key (id_usuario, id_perfil)
);

create table if not exists clientes (
    id_cliente int generated by default as identity primary key,
    id_usuario int not null unique references usuarios(id_usuario) on delete cascade,
    cpf varchar unique,
    telefone varchar,
    data_nascimento date
);

create table if not exists enderecos (
    id_endereco int generated by default as identity primary key,
    id_cliente int not null references clientes(id_cliente) on delete cascade,
    cep varchar,
    logradouro varchar not null,
    numero varchar not null,
    complemento varchar,
    bairro varchar not null,
    cidade varchar not null,
    estado varchar not null,
    tipo varchar,
    principal boolean not null default false
);

create table if not exists categorias (
    id_categoria int generated by default as identity primary key,
    nome varchar not null,
    descricao text,
    status varchar not null default 'ATIVA'
);

create table if not exists produtos (
    id_produto int generated by default as identity primary key,
    id_categoria int references categorias(id_categoria),
    nome varchar not null,
    descricao text,
    preco decimal(10, 2) not null,
    estoque int not null default 0,
    imagem varchar,
    ingredientes text,
    status varchar not null default 'ATIVO',
    data_cadastro timestamp not null default now()
);

create table if not exists pedidos (
    id_pedido int generated by default as identity primary key,
    id_cliente int not null references clientes(id_cliente),
    id_endereco_entrega int not null references enderecos(id_endereco),
    data_pedido timestamp not null default now(),
    status varchar not null,
    valor_frete decimal(10, 2) not null default 0,
    valor_total decimal(10, 2) not null
);

create table if not exists itens_pedido (
    id_item int generated by default as identity primary key,
    id_pedido int not null references pedidos(id_pedido) on delete cascade,
    id_produto int not null references produtos(id_produto),
    quantidade int not null,
    preco_unitario decimal(10, 2) not null,
    subtotal decimal(10, 2) not null
);

create table if not exists pagamentos (
    id_pagamento int generated by default as identity primary key,
    id_pedido int not null references pedidos(id_pedido) on delete cascade,
    metodo varchar not null,
    valor decimal(10, 2) not null,
    status varchar not null,
    data_pagamento timestamp,
    codigo_transacao varchar
);

insert into perfis (nome, descricao)
values
    ('CLIENTE', 'Cliente do e-commerce'),
    ('ADMIN', 'Administrador do sistema'),
    ('ESTOQUISTA', 'Usuario responsavel pelo estoque')
on conflict (nome) do nothing;

alter table categorias enable row level security;
alter table produtos enable row level security;

drop policy if exists "Leitura publica de categorias" on categorias;
create policy "Leitura publica de categorias"
on categorias
for select
to anon, authenticated
using (status = 'ATIVA');

drop policy if exists "Leitura publica de produtos" on produtos;
create policy "Leitura publica de produtos"
on produtos
for select
to anon, authenticated
using (status = 'ATIVO');

grant usage on schema public to anon, authenticated;
grant select on categorias, produtos to anon, authenticated;

commit;
